config/routes.rb
    resource :settings, only: [:edit, :update]
    resources :news_categories, only: [:index, :new, :create, :show, :destroy] do
      collection do
        post :sort
      end
    end

    resources :news_sources, only: [:index, :new, :create, :destroy] do
      post :activate
      post :deactivate
    end

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: {id: /[^\/]+/}

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show, :edit, :update] do
      member do
        post :subscribe
        post :unsubscribe
        post :enable
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
        post :verify
        post :unverify
        post :add_donor_badge
        post :remove_donor_badge
        post :add_investor_badge
        post :remove_investor_badge
        get :edit_pro
        put :save_pro
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :followers, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create, :update, :destroy] do
      member do
        post :copy
        post :enable
        post :disable
      end
    end

    resources :groups, only: [:index, :destroy] do
      member do
        post :enable_featured
        post :disable_featured
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]

    resources :tags, only: [:index] do
      member do
        post :hide
        post :unhide
      end
    end
  end

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # Identity proofs
    get :proofs, to: 'proofs#index'

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :update, :show, :destroy] do
        scope module: :statuses do
          resources :reblogged_by, controller: :reblogged_by_accounts, only: :index
          resources :favourited_by, controller: :favourited_by_accounts, only: :index
          resource :reblog, only: :create
          post :unreblog, to: 'reblogs#destroy'

          resource :favourite, only: :create
          post :unfavourite, to: 'favourites#destroy'

          resource :mute, only: :create
          post :unmute, to: 'mutes#destroy'

          resource :pin, only: :create
          post :unpin, to: 'pins#destroy'
        end

        member do
          get :context
          get :card
          get :revisions
        end
      end

      namespace :timelines do
        resource :direct, only: :show, controller: :direct
        resource :home, only: :show, controller: :home
        resource :public, only: :show, controller: :public
        resources :tag, only: :show
        resources :list, only: :show
        resources :group, only: :show
        resources :news, only: [:index, :show],  controller: :news
      end

      resources :streaming, only: [:index]
      resources :custom_emojis, only: [:index]
      resources :suggestions, only: [:index, :destroy]
      resources :scheduled_statuses, only: [:index, :show, :update, :destroy]
      resources :preferences, only: [:index]
      resources :trends, only: [:index]
      resources :news_categories, only: :index


      resources :conversations, only: [:index, :destroy] do
        member do
          post :read
        end
      end

      get '/search', to: 'search#index', as: :search

      get '/account_by_username/:username', to: 'account_by_username#show', username: /(.*)/

      resources :follows, only: [:create]
      resources :media, only: [:create, :update]
      resources :blocks, only: [:index]
      resources :mutes, only: [:index]
      resources :favourites, only: [:index]
      resources :reports, only: [:create]
      resources :filters, only: [:index, :create, :show, :update, :destroy]
      resources :endorsements, only: [:index]

      namespace :apps do
        get :verify_credentials, to: 'credentials#show'
      end

      resources :apps, only: [:create]

      resource :instance, only: [:show] do
        resources :peers, only: [:index], controller: 'instances/peers'
        resource :activity, only: [:show], controller: 'instances/activity'
      end

      resource :domain_blocks, only: [:show, :create, :destroy]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
          post :dismiss # Deprecated
        end

        member do
          post :dismiss
        end
      end

      namespace :accounts do
        get :verify_credentials, to: 'credentials#show'
        patch :update_credentials, to: 'credentials#update'
        resource :search, only: :show, controller: :search
        resources :relationships, only: :index
      end

      resources :accounts, only: [:create, :show] do
        resources :statuses, only: :index, controller: 'accounts/statuses'
        resources :followers, only: :index, controller: 'accounts/follower_accounts'
        resources :following, only: :index, controller: 'accounts/following_accounts'
        resources :lists, only: :index, controller: 'accounts/lists'
        resources :identity_proofs, only: :index, controller: 'accounts/identity_proofs'

        member do
          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end

        resource :pin, only: :create, controller: 'accounts/pins'
        post :unpin, to: 'accounts/pins#destroy'
      end

      resources :lists, only: [:index, :create, :show, :update, :destroy] do
        resource :accounts, only: [:show, :create, :destroy], controller: 'lists/accounts'
      end

      resources :groups, only: [:index, :create, :show, :update, :destroy] do
        member do
          delete '/statuses/:status_id', to: 'groups#destroy_status'
          post '/statuses/:status_id/approve', to: 'groups#approve_status'
        end

        resources :relationships, only: :index, controller: 'groups/relationships'
        resource :accounts, only: [:show, :create, :update, :destroy], controller: 'groups/accounts'
        resource :removed_accounts, only: [:show, :create, :destroy], controller: 'groups/removed_accounts'
      end

      resources :polls, only: [:create, :show] do
        resources :votes, only: :create, controller: 'polls/votes'
      end

      namespace :push do
        resource :subscription, only: [:create, :show, :update, :destroy]
      end
    end

    namespace :v2 do
      get '/search', to: 'search#index', as: :search
    end

    namespace :web do
      resource :settings, only: [:update]
      resource :embed, only: [:create]
      resources :push_subscriptions, only: [:create] do
        member do
          put :update
        end
      end
    end
  end

  get '/', to: 'about#show', as: :homepage
  get '/about', to: 'about#more'
  get '/about/tos', to: 'about#terms'
  get '/about/privacy', to: 'about#privacy'
  get '/about/investors', to: 'about#investors'
  get '/about/dmca', to: 'about#dmca'
  get '/about/sales', to: 'about#sales'
  get '/about/apps', to: 'about#apps'
  get '/about/moderation', to: 'about#moderation'

  get '/tags/:tag', to: 'home#index'
  get '/:username', to: 'home#index', as: :short_account
  get '/:username/with_replies', to: 'home#index', as: :short_account_with_replies
  get '/:username/media', to: 'home#index', as: :short_account_media
  get '/:username/tagged/:tag', to: 'home#index', as: :short_account_tag
  get '/:username/posts/:statusId/reblogs', to: 'home#index'
  get '/:account_username/posts/:id', to: 'home#index', as: :short_account_status
  get '/:account_username/posts/:id/embed', to: 'statuses#embed', as: :embed_short_account_status

  get '/(*any)', to: 'home#index', as: :web
  root 'home#index'

  # Routes that are now to be used within webapp, but still referenced within application
  # TODO : Consolidate
  get '/explore', to: 'directories#index', as: :explore
  get '/explore/:id', to: 'directories#show', as: :explore_hashtag

  resources :tags, only: [:show]

  match '*unmatched_route',
        via: :all,
        to: 'application#raise_not_found',

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  layout 'public'

  before_action :set_instance_presenter, only: [:show, :more, :terms, :privacy, :investors, :dmca, :sales]

  def show
    if user_signed_in?
      redirect_to "/home"
    else
      @hide_navbar = false
    end
  end

  def more; end
  def terms; end
  def privacy; end
  def investors; end
  def dmca; end
  def sales; end

  private

  def new_user
    User.new.tap do |user|
      user.build_account
      user.build_invite_request
    end
  end

  helper_method :new_user

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end
end

app/views/about/_login.html.haml
= simple_form_for(new_user, url: user_session_path) do |f|
  .fields-group
    - if use_seamless_external_login?
      = f.input :email, placeholder: t('simple_form.labels.defaults.username_or_email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.username_or_email') }, hint: false
    - else
      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.email') }, hint: false

    = f.input :password, placeholder: t('simple_form.labels.defaults.password'), input_html: { 'aria-label' => t('simple_form.labels.defaults.password') }, hint: false

    %p.hint.subtle-hint= link_to t('auth.trouble_logging_in'), new_user_password_path
    
  .actions
    = f.button :button, t('auth.login'), type: :submit, class: 'button button-primary'

app/views/about/_registration.html.haml
= simple_form_for(new_user, url: user_registration_path) do |f|
  .simple_form__overlay-area
    %p.lead= t('about.federation_hint_html', instance: content_tag(:strong, site_hostname))

    .fields-group
      = f.simple_fields_for :account do |account_fields|
        = account_fields.input :username, wrapper: :with_label, label: false, required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.username'), :autocomplete => 'off', placeholder: t('simple_form.labels.defaults.username') }, hint: false, disabled: closed_registrations?

      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.email'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password, placeholder: t('simple_form.labels.defaults.password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password_confirmation, placeholder: t('simple_form.labels.defaults.confirm_password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?

    - if approved_registrations?
      .fields-group
        = f.simple_fields_for :invite_request do |invite_request_fields|
          = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: false

    .fields-group
      = f.input :agreement, as: :boolean, wrapper: :with_label, label: t('auth.checkbox_agreement_html', about_tos_path: about_tos_path), disabled: closed_registrations?

    .actions
      = f.button :button, sign_up_message, type: :submit, class: 'button button-primary', disabled: closed_registrations?

    - if closed_registrations? && @instance_presenter.closed_registrations_message.present?
      .simple_form__overlay-area__overlay
        .simple_form__overlay-area__overlay__content.rich-formatting
          .block-icon= fa_icon 'warning'
          = @instance_presenter.closed_registrations_message.html_safe

app/views/about/apps.html.haml
- content_for :page_title do
  = t('terms.appstitle', instance: site_hostname)

.content
  .box-widget
    .rich-formatting
      %h2 Recommended Apps
      %p
      %p Most people will access Civiq directly withj web browser, however if you prefer You can use Civiq with any of these apps!
      %p
      %p
      %h2 Android
      %p
        %strong
          %a{:href => "https://play.google.com/store/apps/details?id=com.keylesspalace.tusky"} Tusky
        %em (recommended)
        \- a free lightweight client - It supports all features, like photos, videos, lists, custom emojis and is designed according to material guidelines.
      %p
        %strong
          %a{:href => "https://play.google.com/store/apps/details?id=jp.juggler.subwaytooter"} Subway Tooter
        \- a free Mastodon client for Android 5.0 or later.
      %p
        %strong
          %a{:href => "https://play.google.com/store/apps/details?id=app.fedilab.android"} Fedilab
        \- Fedilab is paid multifunctional Android client to access the distributed Fediverse, consisting of micro blogging, photo sharing and video hosting.
      %p
      %h2  iOS
      %p
        %strong
          %a{:href => "https://apps.apple.com/us/app/amarok-for-mastodon/id1214116200?ls=1"} Amaroq
        %em (recommended)
        \- a free and lightweight universal client for any Mastodon instance! Simply enter the instance you belong to, log in, and enjoy the all the wonders of the federated social network from your phone.
      %p
        %a{:href => "https://apps.apple.com/us/app/mast/id1437429129"}
          %strong Mast
        \- a paid app built with iOS design guidelines in mind. It’s as feature-packed as it is gorgeous. With customisable content and themes.
      %p
        %a{:href => "https://apps.apple.com/app/toot/id1229021451?ls=1", :title => "Toot"}
          %strong Toot
        \- a paid client for the Mastodon social network. It is beautiful, and full of character and whimsy.
      %h2{"data-reactid" => "86"} Web
      %p
        %a{:href => "https://pinafore.social/", :title => "Pinafore"}
          %strong Pinafore
        \- web client designed for speed and simplicity.
      %p
        %a{:href => "https://www.halcyon.social/", :title => "Halcyon"}
          %strong Halcyon
        \- A webclient for which looks like Twitter.
      %p
      %h2 Desktop
      %p
        %strong
          %a{:href => "https://whalebird.org/en/desktop/contents"} Whalebird
        \- a client for desktop application
      %p
        %strong
          %a{:href => "https://appcenter.elementary.io/com.github.bleakgrey.tootle/"} Tootle
        \- a client with real-time notifications and multiple accounts support
      %p
        %a{:href => "https://thedesk.top/en/", :title => "The Desk"}
          %strong The Desk
        \- a Japanese client.
      %p
        %a{:href => "https://hyperspace.marquiskurt.net/", :title => "Hyperspace"}
          %strong Hyperspace
        \- clean, fast, and responsive design that scales beautifully across devices.
      %p 
      %h2  SailfishOS
      %p
        %a{:href => "https://openrepos.net/content/dysko/tooter"}
          %strong Tooter
      %p
      %p

app/views/about/dmca.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.content
  .box-widget
    .rich-formatting
      %h1 CIVIQ
      %h2 COPYRIGHT POLICY

      %h3 Reporting Claims of Copyright Infringement

      %p We take claims of copyright infringement seriously. We will respond to notices of alleged copyright infringement that comply with applicable law. 

      %p If you believe any materials accessible on or from this site (the “Website”) infringe your copyright, you may request removal of those materials (or access to them) from the Website by submitting written notification to our copyright agent designated below. 

      %p In accordance with the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act (17 U.S.C. § 512) (”DMCA”), the written notice (the “DMCA Notice”) must include substantially the following:

      %ul
        %li Your physical or electronic signature.
        %li Identification of the copyrighted work you believe to have been infringed or, if the claim involves multiple works on the Website, a representative list of such works.
        %li Identification of the material you believe to be infringing in a sufficiently precise manner to allow us to locate that material.
        %li Adequate information by which we can contact you (including your name, postal address, telephone number, and, if available, email address).
        %li A statement that you have a good faith belief that use of the copyrighted material is not authorized by the copyright owner, its agent, or the law.
        %li A statement that the information in the written notice is accurate.
        %li A statement, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.
        %br

      %p Please send copyright notices to:

      %p
        CIVIQ
        %br
        C/O Fourth Estate
        %br
        Attn: Copyright Agent
        %br
        1717 K Street NW, Suite 900
        %br
        Washington, DC 20006

      %p Or via any contact form at the bottom of this page.

      %p If you fail to comply with all of the requirements of Section 512(c)(3) of the DMCA, your DMCA Notice may not be effective.
      %p Please be aware that if you knowingly materially misrepresent that material or activity on the Website is infringing your copyright, you may be held liable for damages (including costs and attorneys’ fees) under Section 512(f) of the DMCA.
      %br
      %h3 Counter Notification Procedures
      %p If you believe that material you posted on the Website was removed or access to it was disabled by mistake or misidentification, you may file a counter notification with us (a “Counter Notice”) by submitting written notification to our DMCA address (above) Pursuant to the DMCA, the Counter Notice must include substantially the following:
      
      %ul
        %li Your physical or electronic signature.
        %li An identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access disabled.
        %li Adequate information by which we can contact you (including your name, postal address, telephone number, and, if available, email address).
        %li A statement under penalty of perjury by you that you have a good faith belief that the material identified above was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled.
        %li A statement that you will consent to the jurisdiction of the Federal District Court for the judicial district in which your address is located (or if you reside outside the United States for any judicial district in which the Website may be found) and that you will accept service from the person (or an agent of that person) who provided the Website with the complaint at issue.

      %p The DMCA allows us to restore the removed content if the party filing the original DMCA Notice does not file a court action against you within ten business days of receiving the copy of your Counter Notice.
      %p Please be aware that if you knowingly materially misrepresent that material or activity on the Website was removed or disabled by mistake or misidentification, you may be held liable for damages (including costs and attorneys’ fees) under Section 512(f) of the DMCA.
      %br
      %h3 Repeat Infringers

      %p It is our policy in appropriate circumstances to disable and/or terminate the accounts of users who are repeat infringers.

      %hr

      = mail_to 'support@fourthestate.org'

app/views/about/investors.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.content
  .box-widget
    .rich-formatting
      %h2 Investors and Supporters
      %p
      %p Civiq  is free. There is no advertising, monetizing, or data mining of your personal information. Thank you to the following people, organizations and companies who make it possibe:
      %p
        = link_to 'Fourth Estate Public Benefit Corporation', 'https://www.fourthestate.org'

app/views/about/sales.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.content
  .box-widget
    .rich-formatting
      %h2 Terms of Sale
      %p Fourth Estate Public Benefit Corporation ("Fourth Estate, “We” or “CIVIQ”) hereby allow you to access certain premium features or content in exchange for a one-time or recurring fee, as applicable to the relevant features or content, such as our “Pro” enhanced social media offering (collectively, each a “Premium  Service” and collectively the "Premium Services"). Your transactions and any other use of the Premium Services are subject to these Premium Service Terms of Service ("Terms”).

      %h3 1. Your Acceptance
      %p
        By using a Premium Service, you signify your agreement to (1) these Terms of Sale; and (2) CIVIQ’s
        = link_to 'Terms of Service', about_tos_path
        ,
        = link_to 'Privacy Notice', about_privacy_path
        , and
        = link_to 'Copyright Notice', about_dmca_path
        , and all other terms and conditions that generally apply to the Website (as such term is defined in the Terms of Service). Please read the Terms carefully. If you do not understand the Terms, or do not accept any part of them, then you may not use the Premium Services.
      %p Each time you place an order for a Premium Service (including when you order individual subscriptions or items of content), you enter into a separate contract for services on these Terms. When you complete a purchase, you signify that you wish to enter into a binding contract for the provision of the applicable Premium Services.

      %h3 2. Payment, Refund and Cancellation Policy
      %p CIVIQ accepts payment via the current payment method indicated prior to purchase, which may include Bitcoin and/or any other form of payment that we make available to you from time to time. You must tender valid payment or have a valid accepted form of payment on file in order to purchase Premium Services. You agree to abide by any relevant Terms of Service or other legal agreement, whether with CIVIQ or a third party, that governs your use of a given payment processing method. Prices for any Premium Service may change at any time, and CIVIQ does not provide price protection or refunds in the event of a price reduction or promotional offering. You agree to pay for any Premium Service that you order. CIVIQ will charge your credit card or other form of payment for the price listed on the relevant Premium Service offer, along with any additional amounts relating to applicable taxes, bank fees and currency fluctuations. If you purchase any automatically renewing subscriptions, you agree that CIVIQ will charge the payment method on file on the first day of each billing period for the relevant subscription, and if the payment method on file becomes invalid due to an expired credit card or other similar reason and we are unable to charge you on the next billing period, CIVIQ reserves the right to immediately revoke your access to any Premium Service you have ordered until you update your payment method. If you fail to update your payment method within a reasonable amount of time, CIVIQ may cancel your subscription.
      %p Billing periods may be monthly or quarterly. The renewal period applicable to any subscription will be the same as the initial billing period for the Premium Services.
      %p If CIVIQ is required to collect or pay any taxes in connection with your purchase of a Premium Service, such taxes will be charged to you at the time of each purchase transaction. Additionally, if required by law, you are responsible for reporting and paying certain taxes in connection with your purchase and use of a Premium Service. Such taxes may include duties, customs fees, or other taxes (other than income tax), along with any related penalties or interest, as applicable to your purchase or country of purchase.

      %p
        %b REFUNDS:
        all purchases are final.

      %p
        %b SUBSCRIPTION CANCELLATIONS:
        you purchase a subscription to a Premium Service that automatically renews, you may cancel the subscription any time before the end of the current billing period and the cancellation will take effect on the next billing period. You will retain access to the Premium Service from the time you cancel until the start of the next billing period, and will not receive a refund or credit for any remaining days in your current billing period. If you have any questions or need to contact us about cancellation, please send an e-mail to #{mail_to 'support@fourthestate.org'} or write to CIVIQ, marked for the attention of "Support Services," at our business address listed at the bottom of this policy.

      %h3 3. Accessing Premium Services.
      %p Certain types of Premium Services may require you to use a device that meets the system and compatibility requirements for such Premium Service, which may change from time to time. You shall have sole responsibility for obtaining a device which satisfies those requirements.

      %h3 4. License
      %p Your use of the Premium Services must be only for personal, non-commercial use. You agree not to use any Premium Service, in whole or in part in connection with any public presentation even if no fee is charged (except where such use would not constitute a copyright infringement). You are receiving a non-exclusive license to access the Premium Service and all rights, title and interest in the Premium Services (including any content offered through the Premium Services) not expressly granted to you in these Terms are reserved by Fourth Estate and its licensors. If Fourth Estate reasonably determines that you violated any of the terms and conditions of the Premium Service Terms, your rights under this Section 4 will immediately terminate and Fourth Estate may terminate your access to the Premium Service and/or your Fourth Estate account without notice and without refund to you.

      %h3 5. Restrictions
      %p When you use the Premium Service, you may not (or attempt to):

      %ul
        %li violate the Terms of Service;
        %li use the Premium Service in an illegal manner or for an illegal purpose;
        %li share your account password with someone else to allow them to access any Premium Service that such person did not order;
        %li copy, sell, rent, or sublicense the Premium Services to any third party;
        %li circumvent, reverse-engineer, modify, disable, or otherwise tamper with any security technology that Fourth Estate uses to protect the Premium Service or encourage or help anyone else to do so;
        %li access the Premium Service other than by means authorized by Fourth Estate; or
        %li remove any proprietary notices or labels on Premium Services.

      %h3 6. Changes
      %p Fourth Estate reserves the right to change the availability and content of the Premium Services at any time with or without notice to you. In addition, we reserve the right to modify, suspend, or discontinue any Premium Service with or without notice to you and we will not be liable to you or any third party for any such modifications, suspension, or termination. However, this will not affect your ability to request a refund as described above.
      %p
        In certain cases, content available within a Premium Service may become unavailable. Fourth Estate will have no liability to you for any such unavailability. We may also change these Premium Service Terms from time to time so we encourage you to periodically review the most up-to-date version at
        = link_to 'https://civic.social/about/sales'
      %p If the Premium Service Terms change, you will have the opportunity to review the new terms when you next purchase any Premium Service. By completing the purchase, you signify your agreement to the new Premium Service Terms, and further, that they will apply to your use of the Service as a whole (including any Premium Service you have purchased in the past) and all subsequent purchases (until the Premium Service Terms change again). If you refuse to accept the updated Premium Service Terms then you may not buy any additional Premium Services and the latest version of the Premium Service Terms that you accepted will continue to apply to your use of previously purchased Premium Services.

      %h3 7. Communications
      %p By using the Premium Services, you consent to receiving communications from us including marketing communications such as newsletters about features and content, special offers, promotional announcements, and customer surveys, to your registered email address or via other methods.

      %h3 8. Other Terms
      %p You acknowledge and agree that certain content available in the Premium Services may be considered offensive to some people and that such content may not be labeled as such. Additionally, certain descriptions of Premium Services or content available in the Premium Services are not guaranteed to be accurate. You agree to use the Premium Services at your own risk and, subject to applicable laws, Fourth Estate will have no liability to you for any content that you find offensive.

      %p The Premium Services are being provided by the Fourth Estate Public Benefit Corporation, reachable at:

      %p
        CIVIQ
        %br
        c/o Fourth Estate
        %br
        1717 K Street NW, Suite 900
        %br
        Washington, DC 20006
        %br
        United States of America